# Generated by Django 5.1.1 on 2024-09-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='Not Provided', max_length=254),
        ),
    ]
